version: '3.8'

services:
  db:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

# http://localhost:8080/postgres/browser
# add server db host, postgres user, postgres password
  pgadmin4:
    image: dpage/pgadmin4:8.2
    ports:
      - 5050:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - db

volumes:
  postgres-data:
  pgadmin-data: