version: '3.8'

services:
  web:
    image: nginx:alpine3.18-slim
    ports:
      - 8080:80
    volumes:
      - ../docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: node:16.13.0-alpine3.14
    container_name: app
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ..:/app
    working_dir: /app
    command: sh -c "/usr/local/bin/npm install && /usr/local/bin/npm start"

  db:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:8.2
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - db

volumes:
  postgres-data: